set(CPACK_PACKAGE_VENDOR "MBASE Yazilim A.S.")
set(CPACK_PACKAGE_CONTACT "erdog@mbasesoftware.com")
set(CPACK_PACKAGE_VERSION_MAJOR ${MBASE_LIBS_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${MBASE_LIBS_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${MBASE_LIBS_PATCH})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/description.txt)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MBASE SDK")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.mbasesoftware.com")
set(CPACK_SYSTEM_NAME ${MBASE_SYSTEM_NAME})
set(CPACK_RESOURCE_FILE_README ${MBASE_LIBS_README})
set(CPACK_RESOURCE_FILE_LICENSE ${MBASE_LIBS_LICENSE})
set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS 
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE
)

# DEB
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_STRIP_FILES YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

if(MBASE_BUNDLED_INSTALL)
    set(CPACK_PACKAGE_NAME "mbase-bundled")
else()
    set(CPACK_PACKAGE_NAME "mbase")
endif(MBASE_BUNDLED_INSTALL)

if(GGML_CUDA)
    set(CPACK_PACKAGE_NAME "${CPACK_PACKAGE_NAME}-cuda-${MBASE_CUDA_TARGET}")
    if (WIN32)
        set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/legal/LICENSE-full)
        find_package(CUDAToolkit)
        install(
            FILES ${CUDAToolkit_BIN_DIR}/cublas64_${CUDAToolkit_VERSION_MAJOR}.dll ${CUDAToolkit_BIN_DIR}/cublasLt64_${CUDAToolkit_VERSION_MAJOR}.dll ${CUDAToolkit_BIN_DIR}/cudart64_${CUDAToolkit_VERSION_MAJOR}.dll
            DESTINATION ${MBASE_LIBS_BIN_INSTALL_DIR}
        )
        install(
        FILES ${CMAKE_CURRENT_SOURCE_DIR}/legal/cuda_redis_disclaimer
        PERMISSIONS
            OWNER_READ
            OWNER_WRITE
            GROUP_READ
            WORLD_READ
        DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/mbase/license
        )
    endif()
endif()

if(GGML_METAL STREQUAL "ON")
    set(CPACK_PACKAGE_NAME "${CPACK_PACKAGE_NAME}-metal")
endif()

# NSIS
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH ON)
set(CPACK_NSIS_DISPLAY_NAME "MBASE SDK")
set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")
set(CPACK_NSIS_UNINSTALL_NAME "MBASE SDK Uninstall")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "mbase.libs")
set(CPACK_NSIS_BRANDING_TEXT "${CPACK_PACKAGE_VENDOR}")
set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/favicon.ico")
set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/favicon.ico")
#set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/docs/source/favicon.png")

# RPM
# CPACK_RPM_PACKAGE_SUMMARY === CPACK_PACKAGE_DESCRIPTION_SUMMARY
# CPACK_RPM_PACKAGE_NAME === CPACK_PACKAGE_NAME
# CPACK_RPM_PACKAGE_VERSION === CPACK_PACKAGE_VERSION

set(CPACK_RPM_PACKAGE_LICENSE "MIT")

include(CPack)